weather:
  source:
    baseUrl: http://api.openweathermap.org/data/2.5/forecast?
  API:
    key: 1427ab33252ab6a1399d833eaf84e908
  default:
    city:
      nameDefault: London
      countryDefault: UK
    timestamps:
      countDefault: 40
    unitDefault: metric
    langDefault: en
  3day:
    timestamps:
      forecast3day: 24
