weather:
  source:
    url: http://api.openweathermap.org/data/2.5/forecast?

  API:
    Key: 1427ab33252ab6a1399d833eaf84e908

  default:
    city:
      name: London
      country: UK
    timestamps:
      count: 40
    unit: metric
    language: en

  3day:
    timestamps:
      count: 24
